### ISSUE TITLE
Connect WalletAuth to the FEVM chain

### ISSUE THREAD

**Issue by avivash** [webnative-examples/walletauth#14]
We'd like to participate in the [ETH Global Space Warp](https://ethglobal.com/events/spacewarp) hackathon later this month by demoing a WalletAuth <-> FEVM integration.

In theory this should be fairly straightforward, but to test things out we will first need to either run an FEVM node locally or connect to a hosted one. Once that is done, we will record a demo of our WalletAuth template connecting to that chain and running through all the WalletAuth template features

**Comment by walkah** [comment]
Done! Handled directly in metamask
