### ISSUE TITLE
Get Main hooked up to walletauth.fission.app

### ISSUE THREAD

**Issue by bmann** [webnative-examples/walletauth#2]
Instead of https://universal-turquoise-plastic-hydra.fission.app/, let's get the main branch set to be at walletauth.fission.app

PRs and branches can use auto generated names. 

And we can also set up example.walletauth.eth to point to IPNS://walletauth.fission.app (not sure of exact syntax).

**Comment by icidasset** [comment]
Deployed to https://walletauth.fission.app/ via Github action.
